logging:
  level:
    org.h2: debug
    redis.embedded: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:${local.server.h2.port}/${local.server.h2.database};MODE=MySQL;DATABASE_TO_UPPER=false
    username: sa
  thymeleaf:
    cache: false
  exposed:
    show-sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8
      platform: h2
  data:
    redis:
      port: ${local.server.redis.port}

# 로컬 서버 포트 설정
local:
  server:
    redis:
      port: 46379
    h2:
      port: 49090
      database: ~/local
      init: true
