logging:
  level:
    org.h2: debug
    redis.embedded: debug
    org.antop.board: debug

server:
  port: 8888

spring:
  application:
    name: toy-board
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  h2:
    console:
      enabled: false
  exposed:
    show-sql: false

management:
  health:
    redis:
      enabled: true

app:
  file-upload:
    path: /Users/antop/test
