spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/toy_board?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: antop
    password: local
  thymeleaf:
    cache: false
  mail:
    host: localhost
    port: 2525

management:
  health:
    mail:
      enabled: false # 얍 사적 사 SMTP 서버 체크 안함

app:
  site:
    url: http://localhost:8888
  password-reset:
    token-timeout: 10m
  rsa:
    private-key: classpath:rsa/private_key.pem
    public-key: classpath:rsa/public_key.pem

