logging:
  level:
    org.springframework.web: debug
    gg.jte: trace

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/toy_board?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: antop
    password: local

gg:
  jte:
    use-precompiled-templates: false
    development-mode: true
